// <auto-generated />
using System;
using K.Fixer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K.Fixer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("K.Fixer.Domain.IAM.Aggregates.AdminUser.AdminUser", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("RecordId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.IAM.Aggregates.User.User", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("RecordId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.MaintenanceRequest", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("RecordId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.StatusChangeLogEntry", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<long?>("MaintenanceRequestRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_status");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("RecordId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedById");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MaintenanceRequestRecordId");

                    b.HasIndex("RequestId");

                    b.ToTable("maintenance_status_log", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Building", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("RecordId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("building", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Building.ResidentOccupancy", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("RecordId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ResidentId");

                    b.ToTable("resident_assignments", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Company.Company", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("RecordId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Infrastructure.Persistence.Entities.MaintenancePriorityDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_pl");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("maintenance_priority_dict", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Infrastructure.Persistence.Entities.MaintenanceStatusDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_pl");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique();

                    b.ToTable("maintenance_status_dict", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Infrastructure.Persistence.Entities.RoleDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_pl");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("role_dict", (string)null);
                });

            modelBuilder.Entity("K.Fixer.Domain.IAM.Aggregates.User.User", b =>
                {
                    b.HasOne("K.Fixer.Domain.PropertyManagement.Aggregates.Company.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.MaintenanceRequest", b =>
                {
                    b.HasOne("K.Fixer.Domain.IAM.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.WorkPeriod", "WorkPeriod", b1 =>
                        {
                            b1.Property<long>("MaintenanceRequestRecordId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at_utc");

                            b1.Property<DateTime>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_date_at_utc");

                            b1.HasKey("MaintenanceRequestRecordId");

                            b1.HasIndex("CompletedAt");

                            b1.HasIndex("StartedAt");

                            b1.ToTable("maintenance_requests");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceRequestRecordId");
                        });

                    b.Navigation("WorkPeriod");
                });

            modelBuilder.Entity("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.StatusChangeLogEntry", b =>
                {
                    b.HasOne("K.Fixer.Domain.IAM.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.MaintenanceRequest", null)
                        .WithMany("StatusLog")
                        .HasForeignKey("MaintenanceRequestRecordId");
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Building", b =>
                {
                    b.HasOne("K.Fixer.Domain.PropertyManagement.Aggregates.Company.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Address", "Address", b1 =>
                        {
                            b1.Property<long>("BuildingRecordId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_country_code");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_street");

                            b1.HasKey("BuildingRecordId");

                            b1.ToTable("building");

                            b1.WithOwner()
                                .HasForeignKey("BuildingRecordId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Building.ResidentOccupancy", b =>
                {
                    b.HasOne("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Building", null)
                        .WithMany("Occupancies")
                        .HasForeignKey("BuildingId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("K.Fixer.Domain.IAM.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("K.Fixer.Domain.PropertyManagement.Aggregates.Building.OccupancyPeriod", "Period", b1 =>
                        {
                            b1.Property<long>("ResidentOccupancyRecordId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_from");

                            b1.Property<DateTime?>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_to");

                            b1.HasKey("ResidentOccupancyRecordId");

                            b1.HasIndex("From");

                            b1.HasIndex("To");

                            b1.ToTable("resident_assignments");

                            b1.WithOwner()
                                .HasForeignKey("ResidentOccupancyRecordId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Company.Company", b =>
                {
                    b.OwnsOne("K.Fixer.Domain.PropertyManagement.Aggregates.Company.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<long>("CompanyRecordId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("tax_id_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tax_id_number");

                            b1.HasKey("CompanyRecordId");

                            b1.HasIndex("CountryCode", "Number")
                                .IsUnique();

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyRecordId");
                        });

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("K.Fixer.Domain.Maintenance.Aggregates.MaintenanceRequest.MaintenanceRequest", b =>
                {
                    b.Navigation("StatusLog");
                });

            modelBuilder.Entity("K.Fixer.Domain.PropertyManagement.Aggregates.Building.Building", b =>
                {
                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
